version: '3.8'
services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - hilite
    volumes:
      - ./nginx-docker.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    ports:
      - 8080:80
  
  bastion:
    image: praqma/network-multitool
    container_name: bastion
    restart: always    
    networks:
      - my-network

  hilite:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hilite
    networks:
      - my-network
    ports:
      - 5000:5000


networks:
  my-network:
    driver: bridge